version: '3.8'

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../infrastructure/docker/frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api/v1
    networks:
      - bookreview-network

  backend:
    build:
      context: ../../backend
      dockerfile: ../infrastructure/docker/backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=local_development_secret
      - JWT_EXPIRES_IN=60m
    volumes:
      - ../../backend/data:/app/data
    networks:
      - bookreview-network

networks:
  bookreview-network:
    driver: bridge
